<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarnOn>3390;$(WarnOn)</WarnOn>
        <RootNamespace>Fes</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="FSharp.Core"/>
        <PackageReference Include="FSharp.SystemTextJson"/>
    </ItemGroup>
    <ItemGroup>
        <!-- Core library files (before generated code) -->
        <Compile Include="Prelude.fs"/>
        <Compile Include="Task.fs"/>
        <Compile Include="Result.fs"/>
        <Compile Include="TaskResult.fs"/>
        <Compile Include="Exceptions.fs"/>
        <!-- Generated types -->
        <Compile Include="Generated/Types/CoreTypes.g.fs"/>
        <Compile Include="Generated/Types/AsyncSearchStatus.g.fs"/>
        <Compile Include="Generated/Types/AsyncSearchTypes.g.fs"/>
        <Compile Include="Generated/Types/AutoscalingGetAutoscalingCapacity.g.fs"/>
        <Compile Include="Generated/Types/AutoscalingTypes.g.fs"/>
        <Compile Include="Generated/Types/CatAliases.g.fs"/>
        <Compile Include="Generated/Types/CatAllocation.g.fs"/>
        <Compile Include="Generated/Types/CatCircuitBreaker.g.fs"/>
        <Compile Include="Generated/Types/CatComponentTemplates.g.fs"/>
        <Compile Include="Generated/Types/CatCount.g.fs"/>
        <Compile Include="Generated/Types/CatFielddata.g.fs"/>
        <Compile Include="Generated/Types/CatHealth.g.fs"/>
        <Compile Include="Generated/Types/CatIndices.g.fs"/>
        <Compile Include="Generated/Types/CatMaster.g.fs"/>
        <Compile Include="Generated/Types/CatMlDataFrameAnalytics.g.fs"/>
        <Compile Include="Generated/Types/CatMlDatafeeds.g.fs"/>
        <Compile Include="Generated/Types/CatMlJobs.g.fs"/>
        <Compile Include="Generated/Types/CatMlTrainedModels.g.fs"/>
        <Compile Include="Generated/Types/CatNodeattrs.g.fs"/>
        <Compile Include="Generated/Types/CatNodes.g.fs"/>
        <Compile Include="Generated/Types/CatPendingTasks.g.fs"/>
        <Compile Include="Generated/Types/CatPlugins.g.fs"/>
        <Compile Include="Generated/Types/CatRecovery.g.fs"/>
        <Compile Include="Generated/Types/CatRepositories.g.fs"/>
        <Compile Include="Generated/Types/CatSegments.g.fs"/>
        <Compile Include="Generated/Types/CatShards.g.fs"/>
        <Compile Include="Generated/Types/CatSnapshots.g.fs"/>
        <Compile Include="Generated/Types/CatTasks.g.fs"/>
        <Compile Include="Generated/Types/CatTemplates.g.fs"/>
        <Compile Include="Generated/Types/CatThreadPool.g.fs"/>
        <Compile Include="Generated/Types/CatTransforms.g.fs"/>
        <Compile Include="Generated/Types/CatTypes.g.fs"/>
        <Compile Include="Generated/Types/CcrFollowInfo.g.fs"/>
        <Compile Include="Generated/Types/CcrGetAutoFollowPattern.g.fs"/>
        <Compile Include="Generated/Types/CcrStats.g.fs"/>
        <Compile Include="Generated/Types/CcrTypes.g.fs"/>
        <Compile Include="Generated/Types/ClusterAllocationExplain.g.fs"/>
        <Compile Include="Generated/Types/ClusterHealth.g.fs"/>
        <Compile Include="Generated/Types/ClusterPendingTasks.g.fs"/>
        <Compile Include="Generated/Types/ClusterRemoteInfo.g.fs"/>
        <Compile Include="Generated/Types/ClusterReroute.g.fs"/>
        <Compile Include="Generated/Types/ClusterState.g.fs"/>
        <Compile Include="Generated/Types/ClusterStats.g.fs"/>
        <Compile Include="Generated/Types/ClusterTypes.g.fs"/>
        <Compile Include="Generated/Types/ConnectorTypes.g.fs"/>
        <Compile Include="Generated/Types/DanglingIndicesListDanglingIndices.g.fs"/>
        <Compile Include="Generated/Types/EnrichExecutePolicy.g.fs"/>
        <Compile Include="Generated/Types/EnrichStats.g.fs"/>
        <Compile Include="Generated/Types/EnrichTypes.g.fs"/>
        <Compile Include="Generated/Types/EqlSearch.g.fs"/>
        <Compile Include="Generated/Types/EqlTypes.g.fs"/>
        <Compile Include="Generated/Types/EsqlListQueries.g.fs"/>
        <Compile Include="Generated/Types/EsqlTypes.g.fs"/>
        <Compile Include="Generated/Types/FeaturesTypes.g.fs"/>
        <Compile Include="Generated/Types/FleetTypes.g.fs"/>
        <Compile Include="Generated/Types/GlobalBulk.g.fs"/>
        <Compile Include="Generated/Types/GlobalCapabilities.g.fs"/>
        <Compile Include="Generated/Types/GlobalExplain.g.fs"/>
        <Compile Include="Generated/Types/GlobalFieldCaps.g.fs"/>
        <Compile Include="Generated/Types/GlobalGet.g.fs"/>
        <Compile Include="Generated/Types/GlobalGetScriptContext.g.fs"/>
        <Compile Include="Generated/Types/GlobalGetScriptLanguages.g.fs"/>
        <Compile Include="Generated/Types/GlobalHealthReport.g.fs"/>
        <Compile Include="Generated/Types/GlobalKnnSearchTypes.g.fs"/>
        <Compile Include="Generated/Types/GlobalMget.g.fs"/>
        <Compile Include="Generated/Types/GlobalMsearch.g.fs"/>
        <Compile Include="Generated/Types/GlobalMsearchTemplate.g.fs"/>
        <Compile Include="Generated/Types/GlobalMtermvectors.g.fs"/>
        <Compile Include="Generated/Types/GlobalRankEval.g.fs"/>
        <Compile Include="Generated/Types/GlobalReindex.g.fs"/>
        <Compile Include="Generated/Types/GlobalReindexRethrottle.g.fs"/>
        <Compile Include="Generated/Types/GlobalScriptsPainlessExecute.g.fs"/>
        <Compile Include="Generated/Types/GlobalSearch.g.fs"/>
        <Compile Include="Generated/Types/GlobalSearchMvtTypes.g.fs"/>
        <Compile Include="Generated/Types/GlobalSearchShards.g.fs"/>
        <Compile Include="Generated/Types/GlobalSearchTypes.g.fs"/>
        <Compile Include="Generated/Types/GlobalTermvectors.g.fs"/>
        <Compile Include="Generated/Types/GlobalUpdate.g.fs"/>
        <Compile Include="Generated/Types/GlobalUpdateByQueryRethrottle.g.fs"/>
        <Compile Include="Generated/Types/GraphTypes.g.fs"/>
        <Compile Include="Generated/Types/IlmExplainLifecycle.g.fs"/>
        <Compile Include="Generated/Types/IlmGetLifecycle.g.fs"/>
        <Compile Include="Generated/Types/IlmMoveToStep.g.fs"/>
        <Compile Include="Generated/Types/IlmTypes.g.fs"/>
        <Compile Include="Generated/Types/IndicesAddBlock.g.fs"/>
        <Compile Include="Generated/Types/IndicesAnalyze.g.fs"/>
        <Compile Include="Generated/Types/IndicesClose.g.fs"/>
        <Compile Include="Generated/Types/IndicesCreateFrom.g.fs"/>
        <Compile Include="Generated/Types/IndicesDataStreamsStats.g.fs"/>
        <Compile Include="Generated/Types/IndicesDeleteAlias.g.fs"/>
        <Compile Include="Generated/Types/IndicesExplainDataLifecycle.g.fs"/>
        <Compile Include="Generated/Types/IndicesFieldUsageStats.g.fs"/>
        <Compile Include="Generated/Types/IndicesForcemergeTypes.g.fs"/>
        <Compile Include="Generated/Types/IndicesGet.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetAliasTypes.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetDataLifecycle.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetDataLifecycleStats.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetDataStreamMappings.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetDataStreamOptions.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetDataStreamSettings.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetFieldMapping.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetIndexTemplate.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetMapping.g.fs"/>
        <Compile Include="Generated/Types/IndicesGetMigrateReindexStatus.g.fs"/>
        <Compile Include="Generated/Types/IndicesMigrateReindex.g.fs"/>
        <Compile Include="Generated/Types/IndicesModifyDataStream.g.fs"/>
        <Compile Include="Generated/Types/IndicesPutDataStreamMappings.g.fs"/>
        <Compile Include="Generated/Types/IndicesPutDataStreamSettings.g.fs"/>
        <Compile Include="Generated/Types/IndicesPutIndexTemplate.g.fs"/>
        <Compile Include="Generated/Types/IndicesRecovery.g.fs"/>
        <Compile Include="Generated/Types/IndicesReloadSearchAnalyzers.g.fs"/>
        <Compile Include="Generated/Types/IndicesRemoveBlock.g.fs"/>
        <Compile Include="Generated/Types/IndicesResolveCluster.g.fs"/>
        <Compile Include="Generated/Types/IndicesResolveIndex.g.fs"/>
        <Compile Include="Generated/Types/IndicesRollover.g.fs"/>
        <Compile Include="Generated/Types/IndicesSegments.g.fs"/>
        <Compile Include="Generated/Types/IndicesShardStores.g.fs"/>
        <Compile Include="Generated/Types/IndicesSimulateTemplate.g.fs"/>
        <Compile Include="Generated/Types/IndicesStats.g.fs"/>
        <Compile Include="Generated/Types/IndicesTypes.g.fs"/>
        <Compile Include="Generated/Types/IndicesUpdateAliases.g.fs"/>
        <Compile Include="Generated/Types/IndicesValidateQuery.g.fs"/>
        <Compile Include="Generated/Types/InferenceTypes.g.fs"/>
        <Compile Include="Generated/Types/IngestGeoIpStats.g.fs"/>
        <Compile Include="Generated/Types/IngestGetGeoipDatabase.g.fs"/>
        <Compile Include="Generated/Types/IngestGetIpLocationDatabase.g.fs"/>
        <Compile Include="Generated/Types/IngestTypes.g.fs"/>
        <Compile Include="Generated/Types/LicenseGet.g.fs"/>
        <Compile Include="Generated/Types/LicensePost.g.fs"/>
        <Compile Include="Generated/Types/LicenseTypes.g.fs"/>
        <Compile Include="Generated/Types/LogstashTypes.g.fs"/>
        <Compile Include="Generated/Types/MigrationDeprecations.g.fs"/>
        <Compile Include="Generated/Types/MigrationGetFeatureUpgradeStatus.g.fs"/>
        <Compile Include="Generated/Types/MigrationPostFeatureUpgrade.g.fs"/>
        <Compile Include="Generated/Types/MlEvaluateDataFrame.g.fs"/>
        <Compile Include="Generated/Types/MlGetCalendars.g.fs"/>
        <Compile Include="Generated/Types/MlGetMemoryStats.g.fs"/>
        <Compile Include="Generated/Types/MlInfo.g.fs"/>
        <Compile Include="Generated/Types/MlPreviewDataFrameAnalytics.g.fs"/>
        <Compile Include="Generated/Types/MlPutTrainedModel.g.fs"/>
        <Compile Include="Generated/Types/MlTypes.g.fs"/>
        <Compile Include="Generated/Types/NodesClearRepositoriesMeteringArchive.g.fs"/>
        <Compile Include="Generated/Types/NodesGetRepositoriesMeteringInfo.g.fs"/>
        <Compile Include="Generated/Types/NodesInfo.g.fs"/>
        <Compile Include="Generated/Types/NodesReloadSecureSettings.g.fs"/>
        <Compile Include="Generated/Types/NodesStats.g.fs"/>
        <Compile Include="Generated/Types/NodesTypes.g.fs"/>
        <Compile Include="Generated/Types/NodesUsage.g.fs"/>
        <Compile Include="Generated/Types/ProfilingStatus.g.fs"/>
        <Compile Include="Generated/Types/ProjectTags.g.fs"/>
        <Compile Include="Generated/Types/ProjectTypes.g.fs"/>
        <Compile Include="Generated/Types/QueryRulesListRulesets.g.fs"/>
        <Compile Include="Generated/Types/QueryRulesTest.g.fs"/>
        <Compile Include="Generated/Types/QueryRulesTypes.g.fs"/>
        <Compile Include="Generated/Types/RollupGetJobs.g.fs"/>
        <Compile Include="Generated/Types/RollupGetRollupCaps.g.fs"/>
        <Compile Include="Generated/Types/RollupGetRollupIndexCaps.g.fs"/>
        <Compile Include="Generated/Types/RollupTypes.g.fs"/>
        <Compile Include="Generated/Types/SearchApplicationPutBehavioralAnalytics.g.fs"/>
        <Compile Include="Generated/Types/SearchApplicationTypes.g.fs"/>
        <Compile Include="Generated/Types/SearchableSnapshotsCacheStats.g.fs"/>
        <Compile Include="Generated/Types/SearchableSnapshotsMount.g.fs"/>
        <Compile Include="Generated/Types/SearchableSnapshotsTypes.g.fs"/>
        <Compile Include="Generated/Types/SecurityAuthenticate.g.fs"/>
        <Compile Include="Generated/Types/SecurityCreateServiceToken.g.fs"/>
        <Compile Include="Generated/Types/SecurityDelegatePki.g.fs"/>
        <Compile Include="Generated/Types/SecurityDeletePrivileges.g.fs"/>
        <Compile Include="Generated/Types/SecurityEnrollKibana.g.fs"/>
        <Compile Include="Generated/Types/SecurityGetRole.g.fs"/>
        <Compile Include="Generated/Types/SecurityGetServiceAccounts.g.fs"/>
        <Compile Include="Generated/Types/SecurityGetServiceCredentials.g.fs"/>
        <Compile Include="Generated/Types/SecurityGetToken.g.fs"/>
        <Compile Include="Generated/Types/SecurityGetUserProfile.g.fs"/>
        <Compile Include="Generated/Types/SecurityGrantApiKey.g.fs"/>
        <Compile Include="Generated/Types/SecurityHasPrivileges.g.fs"/>
        <Compile Include="Generated/Types/SecurityHasPrivilegesUserProfile.g.fs"/>
        <Compile Include="Generated/Types/SecurityPutPrivileges.g.fs"/>
        <Compile Include="Generated/Types/SecurityQueryApiKeys.g.fs"/>
        <Compile Include="Generated/Types/SecurityQueryRole.g.fs"/>
        <Compile Include="Generated/Types/SecurityQueryUser.g.fs"/>
        <Compile Include="Generated/Types/SecuritySuggestUserProfiles.g.fs"/>
        <Compile Include="Generated/Types/SecurityTypes.g.fs"/>
        <Compile Include="Generated/Types/ShutdownGetNode.g.fs"/>
        <Compile Include="Generated/Types/ShutdownTypes.g.fs"/>
        <Compile Include="Generated/Types/SimulateIngest.g.fs"/>
        <Compile Include="Generated/Types/SlmTypes.g.fs"/>
        <Compile Include="Generated/Types/SnapshotCleanupRepository.g.fs"/>
        <Compile Include="Generated/Types/SnapshotGet.g.fs"/>
        <Compile Include="Generated/Types/SnapshotRepositoryAnalyze.g.fs"/>
        <Compile Include="Generated/Types/SnapshotRestore.g.fs"/>
        <Compile Include="Generated/Types/SnapshotTypes.g.fs"/>
        <Compile Include="Generated/Types/SnapshotVerifyRepository.g.fs"/>
        <Compile Include="Generated/Types/SqlQuery.g.fs"/>
        <Compile Include="Generated/Types/SqlTypes.g.fs"/>
        <Compile Include="Generated/Types/SslCertificates.g.fs"/>
        <Compile Include="Generated/Types/StreamsStatus.g.fs"/>
        <Compile Include="Generated/Types/StreamsTypes.g.fs"/>
        <Compile Include="Generated/Types/SynonymsGetSynonymsSets.g.fs"/>
        <Compile Include="Generated/Types/SynonymsTypes.g.fs"/>
        <Compile Include="Generated/Types/TasksTypes.g.fs"/>
        <Compile Include="Generated/Types/TextStructureFindStructure.g.fs"/>
        <Compile Include="Generated/Types/TextStructureTestGrokPattern.g.fs"/>
        <Compile Include="Generated/Types/TextStructureTypes.g.fs"/>
        <Compile Include="Generated/Types/TransformGetNodeStats.g.fs"/>
        <Compile Include="Generated/Types/TransformGetTransform.g.fs"/>
        <Compile Include="Generated/Types/TransformGetTransformStats.g.fs"/>
        <Compile Include="Generated/Types/TransformTypes.g.fs"/>
        <Compile Include="Generated/Types/WatcherExecuteWatch.g.fs"/>
        <Compile Include="Generated/Types/WatcherStats.g.fs"/>
        <Compile Include="Generated/Types/WatcherTypes.g.fs"/>
        <Compile Include="Generated/Types/XpackInfo.g.fs"/>
        <Compile Include="Generated/Types/XpackUsage.g.fs"/>
        <!-- Generated converters -->
        <Compile Include="Generated/Converters.g.fs"/>
        <!-- Core library files (after types/converters) -->
        <Compile Include="Json.fs"/>
        <Compile Include="Http.fs"/>
        <!-- Generated builders -->
        <Compile Include="Generated/Builders/AsyncSearchStatusBuilders.g.fs"/>
        <Compile Include="Generated/Builders/AsyncSearchTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/AutoscalingGetAutoscalingCapacityBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatAliasesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatAllocationBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatCircuitBreakerBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatCountBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatFielddataBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatHealthBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatIndicesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatMasterBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatMlDataFrameAnalyticsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatMlDatafeedsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatMlJobsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatMlTrainedModelsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatNodeattrsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatNodesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatPendingTasksBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatPluginsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatRecoveryBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatRepositoriesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatSegmentsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatShardsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatSnapshotsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatTasksBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatTemplatesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatThreadPoolBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CatTransformsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CcrFollowInfoBuilders.g.fs"/>
        <Compile Include="Generated/Builders/CcrTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/ClusterAllocationExplainBuilders.g.fs"/>
        <Compile Include="Generated/Builders/ClusterHealthBuilders.g.fs"/>
        <Compile Include="Generated/Builders/ClusterRerouteBuilders.g.fs"/>
        <Compile Include="Generated/Builders/ClusterStatsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/ClusterTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/ConnectorTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/EnrichTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/EqlTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/EsqlTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalBulkBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalFieldCapsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalGetBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalHealthReportBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalMgetBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalMsearchBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalMsearchTemplateBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalMtermvectorsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalRankEvalBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalReindexBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalSearchBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalSearchShardsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalSearchTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GlobalTermvectorsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/GraphTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IlmExplainLifecycleBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IlmMoveToStepBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IlmTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesAnalyzeBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesCreateFromBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesExplainDataLifecycleBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesModifyDataStreamBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesPutDataStreamMappingsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesPutIndexTemplateBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesRecoveryBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesRemoveBlockBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesResolveClusterBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesResolveIndexBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesRolloverBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesShardStoresBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesStatsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesUpdateAliasesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IndicesValidateQueryBuilders.g.fs"/>
        <Compile Include="Generated/Builders/InferenceTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IngestGetIpLocationDatabaseBuilders.g.fs"/>
        <Compile Include="Generated/Builders/IngestTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/LicenseGetBuilders.g.fs"/>
        <Compile Include="Generated/Builders/LicenseTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/MigrationDeprecationsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/MlEvaluateDataFrameBuilders.g.fs"/>
        <Compile Include="Generated/Builders/MlGetMemoryStatsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/MlInfoBuilders.g.fs"/>
        <Compile Include="Generated/Builders/MlPreviewDataFrameAnalyticsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/MlPutTrainedModelBuilders.g.fs"/>
        <Compile Include="Generated/Builders/MlTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/NodesInfoBuilders.g.fs"/>
        <Compile Include="Generated/Builders/NodesTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/QueryRulesTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/RollupGetJobsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/RollupGetRollupCapsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/RollupGetRollupIndexCapsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/RollupTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SearchApplicationTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityAuthenticateBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityDelegatePkiBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityGetRoleBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityGrantApiKeyBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityHasPrivilegesUserProfileBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityPutPrivilegesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityQueryApiKeysBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityQueryRoleBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityQueryUserBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecuritySuggestUserProfilesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SecurityTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SimulateIngestBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SlmTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SnapshotGetBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SnapshotRepositoryAnalyzeBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SnapshotTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/SpecUtilsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TasksTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TextStructureTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TransformGetTransformBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TransformGetTransformStatsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TransformTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TypesAggregationsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TypesAnalysisBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TypesMappingBuilders.g.fs"/>
        <Compile Include="Generated/Builders/TypesQueryDslBuilders.g.fs"/>
        <Compile Include="Generated/Builders/WatcherExecuteWatchBuilders.g.fs"/>
        <Compile Include="Generated/Builders/WatcherStatsBuilders.g.fs"/>
        <Compile Include="Generated/Builders/WatcherTypesBuilders.g.fs"/>
        <Compile Include="Generated/Builders/XpackInfoBuilders.g.fs"/>
        <Compile Include="Generated/Builders/XpackUsageBuilders.g.fs"/>
        <!-- Generated operations -->
        <Compile Include="Generated/Operations/AsyncSearch.g.fs"/>
        <Compile Include="Generated/Operations/Autoscaling.g.fs"/>
        <Compile Include="Generated/Operations/Cat.g.fs"/>
        <Compile Include="Generated/Operations/Ccr.g.fs"/>
        <Compile Include="Generated/Operations/Cluster.g.fs"/>
        <Compile Include="Generated/Operations/Connector.g.fs"/>
        <Compile Include="Generated/Operations/DanglingIndices.g.fs"/>
        <Compile Include="Generated/Operations/Enrich.g.fs"/>
        <Compile Include="Generated/Operations/Eql.g.fs"/>
        <Compile Include="Generated/Operations/Esql.g.fs"/>
        <Compile Include="Generated/Operations/Features.g.fs"/>
        <Compile Include="Generated/Operations/Fleet.g.fs"/>
        <Compile Include="Generated/Operations/Global.g.fs"/>
        <Compile Include="Generated/Operations/Graph.g.fs"/>
        <Compile Include="Generated/Operations/Ilm.g.fs"/>
        <Compile Include="Generated/Operations/Indices.g.fs"/>
        <Compile Include="Generated/Operations/Inference.g.fs"/>
        <Compile Include="Generated/Operations/Ingest.g.fs"/>
        <Compile Include="Generated/Operations/License.g.fs"/>
        <Compile Include="Generated/Operations/Logstash.g.fs"/>
        <Compile Include="Generated/Operations/Migration.g.fs"/>
        <Compile Include="Generated/Operations/Ml.g.fs"/>
        <Compile Include="Generated/Operations/Monitoring.g.fs"/>
        <Compile Include="Generated/Operations/Nodes.g.fs"/>
        <Compile Include="Generated/Operations/Profiling.g.fs"/>
        <Compile Include="Generated/Operations/Project.g.fs"/>
        <Compile Include="Generated/Operations/QueryRules.g.fs"/>
        <Compile Include="Generated/Operations/Rollup.g.fs"/>
        <Compile Include="Generated/Operations/SearchApplication.g.fs"/>
        <Compile Include="Generated/Operations/SearchableSnapshots.g.fs"/>
        <Compile Include="Generated/Operations/Security.g.fs"/>
        <Compile Include="Generated/Operations/Shutdown.g.fs"/>
        <Compile Include="Generated/Operations/Simulate.g.fs"/>
        <Compile Include="Generated/Operations/Slm.g.fs"/>
        <Compile Include="Generated/Operations/Snapshot.g.fs"/>
        <Compile Include="Generated/Operations/Sql.g.fs"/>
        <Compile Include="Generated/Operations/Ssl.g.fs"/>
        <Compile Include="Generated/Operations/Streams.g.fs"/>
        <Compile Include="Generated/Operations/Synonyms.g.fs"/>
        <Compile Include="Generated/Operations/Tasks.g.fs"/>
        <Compile Include="Generated/Operations/TextStructure.g.fs"/>
        <Compile Include="Generated/Operations/Transform.g.fs"/>
        <Compile Include="Generated/Operations/Watcher.g.fs"/>
        <Compile Include="Generated/Operations/Xpack.g.fs"/>
        <Compile Include="Generated/Operations/ES.g.fs"/>
    </ItemGroup>
</Project>
