<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <!-- Main dependencies -->
        <PackageVersion Include="Elastic.Transport" Version="0.15.1" />
        <PackageVersion Include="FSharp.Core" Version="10.0.102" />
        <PackageVersion Include="FSharp.SystemTextJson" Version="1.4.36" />
        <!-- Test dependencies -->
        <PackageVersion Include="FSharpPlus" Version="1.9.1" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageVersion Include="xunit" Version="2.9.3" />
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageVersion Include="coverlet.collector" Version="6.0.4" />
        <PackageVersion Include="FsUnit.xUnit" Version="7.1.1" />
    </ItemGroup>
</Project>
